### ISSUE TITLE
How to make a Call to the Trello API with react-trello-client?

### ISSUE THREAD

**Issue by prclm** [Irandoust/react-trello-client#4]
Hello,

I try to get this to work :D I do not have much experience with react and maybe i miss something.

Authorization works fine. But then i want to make requests to the Trello API.

in the regular client.js by trello i would do something like: 
`window.Trello.rest("GET", "members/me", (res) => console.log(res), err => console.log(err));`

when i try this from my react component, i get an error.

can I do something like
`import Trello from "react-trello-client"`
to use the Trello Object in my component to not use window.Trello?

Maybe you can include a small example in the README?

Thanks!

**Comment by Irandoust** [comment]
Dear @prclm,
Sorry for my late reply. I was so busy for the two weeks. The package supports all the features of the client.js file without importing any other variable or function. You can simply call client methods just by calling `Trello` instead of `window.Trello`. for example: 

`Trello.rest("GET", "members/me", (res) => console.log(res), err => console.log(err));`

I'll update the readme file with some new usage examples today or tomorrow.

Feel free to ask any questions.

**Comment by prclm** [comment]
Thank you @Irandoust for your answer.🙂

There are two things that i don't get working.

I want to use your Plugin in Create-React-App. So I imported "TrelloClient" in my App.js and used the "authorizeButton" for authentication. This works fine.

But if I want to use the "Trello" Object in my App.js, i get the compiling error "Trello" is not defined. (This is why i came up with "window.Trello", which works).

The second problem comes with the API Call,
when i try `Trello.rest("GET", "members/me", (res) => console.log(res), err => console.log(err));` from the Browsers Terminal or `window.Trello.rest("GET", "members/me", (res) => console.log(res), err => console.log(err));` from App.js.

I get the error: **index.js:200 Uncaught (in promise) TypeError: error.json is not a function
    at index.js:200**

"TypeError: Failed to execute 'fetch' on 'Window': Request with GET/HEAD method cannot have body.
    at ajax (http://localhost:3000/static/js/0.chunk.js:36315:14)
    at Object.rest (http://localhost:3000/static/js/0.chunk.js:36412:16)
    at Object.Trello.<computed> [as get] (http://localhost:3000/static/js/0.chunk.js:36654:26)
    at <anonymous>:1:8"

I hope you can make me understand, what i am doing wrong? If the same thing with the original Trello client.js with jquery, it works...

**Comment by Irandoust** [comment]
Dear @prclm 
Sorry for the late reply. I was so busy at my work and had no time to develop and maintain the package. I've updated the package with API options and Trello object, so far to fix the object error.
For the second question, I really recommend reading [this article on medium](https://medium.com/@teogenesmoura/fetching-data-from-trello-private-boards-bb4fcc8a830d) by Teógenes Moura, and [Trello clientjs docs](https://developers.trello.com/docs/clientjs).
I don't know if this late reply helps you, but I hope to help others in the future for the same errors. Sorry again for the late reply and thanks for using the package.
I will close the issue due it's old, but please open a new one if there is any other issue.

**Comment by russ-ab** [comment]
@Irandoust, did you really updated the package? Still getting json about error after authorize 😭 

```
Uncaught (in promise) TypeError: error.json is not a function
    at index.js:177
```

**Comment by prclm** [comment]
> @Irandoust, did you really updated the package? Still getting json about error after authorize 😭
> 

I tried it again and still get the same error, too.

```
Uncaught (in promise) TypeError: e.json is not a function
    at index.js:177
```

@Irandoust thank you for helping out with the article and the docs. I did some testing with the jquery-clientjs by trello, which worked fine. So maybe you can have a look again, if there is any wrong definition or anything else in the code...

**Comment by Irandoust** [comment]
@russ-ab @prclm Yes, you are right. I checked again and there was some problem with headers of the request, in addition, the `json()` method for the responses which not needed at all. I fixed it in the new bugfix version. I tested and now accessing the object is possible. Please download the new version `1.1.3` and revert if the was an issue. Sorry for the mistake.
Thanks

**Comment by russ-ab** [comment]
@Irandoust 

I upgraded plugin version to `1.1.4` and the `json()` problem is fixed.

Now we have another problem with requests returning error 400.

Check it here: https://codesandbox.io/s/serene-hooks-nzgdi

**Comment by Irandoust** [comment]
@russ-ab Thanks for report the issue. Unfortunately, I had some mistakes on the ajax request function. Fixed the bug, also made some refactoring to the code. **Please update to 1.1.6** and revert if there was an issue again, but as I checked it works fine now. I'm trying to spend some more time to write the test for the package for future development.

**Comment by prclm** [comment]
Perfekt now it works fine :) Thank you @Irandoust!

**Comment by Irandoust** [comment]
Thanks for your patient, using the package and report issues.
